name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Setup GitHub Token
        # run: git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        run: npx semantic-release
